### ISSUE TITLE
Add Hackerearth Problems and Solutions

### ISSUE THREAD

**Issue by Vishruth-S** [TLE-MEC/Hack-CP-DSA#124]
Add problems & solutions from [Hackeearth](https://www.hackerearth.com/) in the ```Hackerearth``` folder

**Comment by YushChaudhary** [comment]
can you assign me this issue. Thanks

**Comment by ViniciusLNavarra** [comment]
Could I also take on this Issue?

**Comment by akarshan2602** [comment]
Hey, can i work on this?

**Comment by Vishruth-S** [comment]
This issue to open to all, you may send a Pull Request after reading the [Contributing](https://github.com/TLE-MEC/Hack-CP-DSA/blob/main/CONTRIBUTING.md) guidelines.
