### ISSUE TITLE
Add Hackerrank Problems & Solutions

### ISSUE THREAD

**Issue by Vishruth-S** [TLE-MEC/Hack-CP-DSA#13]
Add problems and solutions from [Hackerrank](https://hackerrank.com) in the ```Hackerrank``` folder

**Comment by saisumanthkumar** [comment]
@Vishruth-S I want to add nearly 30 problems and its solusions, Can I ??

**Comment by Vishruth-S** [comment]
@saisumanthkumar You can add them as long as they follow the guidelines given [here](https://github.com/TLE-MEC/Hack-CP-DSA/blob/main/CONTRIBUTING.md)

**Comment by saisumanthkumar** [comment]
Can i add all of them in Single PR or multiple PR's

**Comment by Vishruth-S** [comment]
@saisumanthkumar You can add them in a single PR or 2-3 PRs. Also it would be preferred if you limit the number of problems to 5  since we would want everyone to have a chance. Thanks!

**Comment by saisumanthkumar** [comment]
ok

**Comment by saisumanthkumar** [comment]
@Vishruth-S Please check PR #67 
Added 3 problems and their solutions

**Comment by saisumanthkumar** [comment]
#67

**Comment by YushChaudhary** [comment]
Is this issue still available.

**Comment by baidya45** [comment]
is the issue still there to work on

**Comment by aryabagde** [comment]
Guys, I added pulled a request and it got merged still there is no sign of that in hacktoberfest?

**Comment by ravi4713** [comment]
Guys, I have added Hackerrank question answer and made a pull request please review that

**Comment by Vishruth-S** [comment]
@YushChaudhary , @baidya45  Yes this issue is still open to all. You may send a Pull request after going  through the contribution guidelines

**Comment by Vishruth-S** [comment]
@aryabagde You should be able to see it in your hacktoberfest profile, please check once more

**Comment by Vishruth-S** [comment]
@ravi4713 Please check your PR and make the necessary changes for it to be approved

**Comment by ravi4713** [comment]
@Vishruth-S 
I have added Comments Now

**Comment by adviksinghania** [comment]
Hello @Vishruth-S ,
Can I add solutions for Project Euler questions which are integrated in HackerRank ?
