### ISSUE TITLE
Add Leetcode Problems & Solutions

### ISSUE THREAD

**Issue by Vishruth-S** [TLE-MEC/Hack-CP-DSA#14]
Add problems and solutions from [Leetcode](https://leetcode.com) in the ```Leetcode``` folder

**Comment by SugatoBagchi** [comment]
Hey, can I add a solution to this?

**Comment by ASLManasa** [comment]
Hi, I am a participant of Hacktoberfest. I would like to add some questions.Can you please assign me this issue. Thank you

**Comment by Vishruth-S** [comment]
@SugatoBagchi Sure, please refer the [Contributing.md](https://github.com/TLE-MEC/Hack-CP-DSA/blob/main/CONTRIBUTING.md) file for contributing guidelines

**Comment by SugatoBagchi** [comment]
> @SugatoBagchi Sure, please refer the [Contributing.md](https://github.com/TLE-MEC/Hack-CP-DSA/blob/main/CONTRIBUTING.md) file for contributing guidelines

On it

**Comment by Vishruth-S** [comment]
@ASLManasa you can add questions, please refer the [Contributing.md](https://github.com/TLE-MEC/Hack-CP-DSA/blob/main/CONTRIBUTING.md), The issue is open to all

**Comment by SUSHANT731** [comment]
We have to raise issue for particular question or directly add it and make a pull request?

**Comment by TechSpiritSS** [comment]
Can you assign me to add C++ solution for this problem.
https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/

**Comment by CSAURABH** [comment]
@Vishruth-S can i work on this issue

**Comment by souvikrajsingh** [comment]
hey, @Vishruth-S  can I add a java Solution to some of the programs? since java and Cpp both are the most used languages in DSA and CP

**Comment by raikiran07** [comment]
Hi @Vishruth-S , can we add any type of leet code problems and it's solution?

**Comment by Vishruth-S** [comment]
Yeah sure, please go through [Contributing](https://github.com/TLE-MEC/Hack-CP-DSA/blob/main/CONTRIBUTING.md) before sending a PR.

**Comment by raikiran07** [comment]
@Vishruth-S  while working on another leetcode problem, I tried to add local directory to the remote repo in github but I am getting some issue, it will be a great help if you could help me out or provide me with some reference.

**Comment by raikiran07** [comment]
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   ../Hackerrank/Drawing Book/Readme.md
        modified:   Median of Two Sorted Arrays/README.md
this issue is coming whenever I try to commit after adding my files.
