### ISSUE TITLE
Add codechef problems & solutions

### ISSUE THREAD

**Issue by Vishruth-S** [TLE-MEC/Hack-CP-DSA#15]
Add problems & solutions from [Codechef](https://www.codechef.com/) in the `Codechef` folder.  

Make sure to go through [Contributing.md](https://github.com/TLE-MEC/Hack-CP-DSA/blob/main/CONTRIBUTING.md) before sending a Pull Request. **Any PR that doesn't adhere to the contributing guidelines will be marked as invalid and closed.**

**Comment by joshiaastha** [comment]
I would like to add solutions for Codechef problems in C++ and Python. Could you please assign this issue to me?

**Comment by KMayank02** [comment]
I would like to add solution of this problem in C++.
https://www.codechef.com/AUG21C/problems/SPCTRIPS
