### ISSUE TITLE
Solution needed for this Hackerrank Problem

### ISSUE THREAD

**Issue by Vishruth-S** [TLE-MEC/Hack-CP-DSA#187]
Add your solution for the Hackerrank problem: [Day of the programmer](https://www.hackerrank.com/challenges/day-of-the-programmer/problem). in this [folder](https://github.com/TLE-MEC/Hack-CP-DSA/tree/main/Hackerrank/Day%20of%20the%20programmer) 

This issue is open to all, and you may directly send a PR after going through the contributing guidelines given [here](https://github.com/TLE-MEC/Hack-CP-DSA/blob/main/CONTRIBUTING.md)

Happy contributing!

**Comment by Vishruth-S** [comment]
All PRs related to this issue will be reviewed, closing this.

**Comment by Meghwantsingh** [comment]
Hi'
I'm Meghwant singh . I'm new to this hacktoberfest but I would like to work on this problem.
I knew C/C++ .
