### ISSUE TITLE
Solution needed to this HackerRank problem

### ISSUE THREAD

**Issue by hannasalam** [TLE-MEC/Hack-CP-DSA#23]
A simple solution with a brief explanation of the logic for this problem:  [Drawing book](https://www.hackerrank.com/challenges/drawing-book/problem)

**Comment by guddu75** [comment]
Hi @hannasalam  can i work on this issue .

**Comment by hannasalam** [comment]
Sure,
This issue is open to all.(multiple solutions in different languages are welcome)

**Comment by Manoj-Suru** [comment]
Hi @hannasalam  please assign me this issue I have solved it.

**Comment by parth93QA** [comment]
Hi I would like to give the solution in python

**Comment by sumitmohite0501** [comment]
Please assign to me . i will solve in Javascript

**Comment by hannasalam** [comment]
@raikiran07 @parth93QA @Manoj-Suru @sumitmohite0501 This issue is open for all. You can contribute. Make sure the follow the contribution guidelines. And you can contribute questions other than this also to the repo.

**Comment by guddu75** [comment]
Hi @hannasalam  . I created a [pull request](https://github.com/TLE-MEC/Hack-CP-DSA/pull/57) to resolve this issue .
