### ISSUE TITLE
Solution needed for Leetcode Problem

### ISSUE THREAD

**Issue by hannasalam** [TLE-MEC/Hack-CP-DSA#30]
Add a simple solution with brief explanation for this problem [Jump Game](https://leetcode.com/problems/jump-game/)

**Comment by sumitmohite0501** [comment]
please assign to me

**Comment by SugatoBagchi** [comment]
Hey, I would like to add a java explanation for this code. Please assign me this issue.

**Comment by hannasalam** [comment]
@sumitmohite0501 @SugatoBagchi This issue is open for all. You can contribute to this. Make sure to follow the contribution guidelines.

**Comment by SugatoBagchi** [comment]
#46 Opened a PR.
