### ISSUE TITLE
Add Codeforces problems & Solutions

### ISSUE THREAD

**Issue by Vishruth-S** [TLE-MEC/Hack-CP-DSA#31]
Add problems and solutions from [Codeforces](https://codeforces.com/) in the ```Codeforces``` folder

**Comment by geoffgeorgein** [comment]
I can contribute a codeforces problem.Please assign me.

**Comment by sumitmohite0501** [comment]
Please assign to me

**Comment by Vishruth-S** [comment]
This issue is open to all. You can directly submit a PR, please refer to the Contributing guidelines given [here](https://github.com/TLE-MEC/Hack-CP-DSA/blob/main/CONTRIBUTING.md)

**Comment by navjotdadwal** [comment]
Sir please assign this issue to me

Why you should assign this to me?
i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234
So i can handle and solve this issue

**Comment by Vishruth-S** [comment]
@navjotdadwal  This issue is open to anyone and doesn't require to be assigned to any single person. You are free to contribute by sending a PR. Please refer the guidelines given [here](https://github.com/TLE-MEC/Hack-CP-DSA/blob/main/CONTRIBUTING.md), Thanks!

**Comment by copyNinja1219** [comment]
Added codeforces problem - Medium Maximization #163
