### ISSUE TITLE
Add Interviewbit problems and solutions

### ISSUE THREAD

**Issue by Vishruth-S** [TLE-MEC/Hack-CP-DSA#483]
Add problems and solutions from [Interviewbit](https://www.interviewbit.com/) in the ```InterviewBit``` folder.

Make sure to go through [Contributing.md](https://github.com/TLE-MEC/Hack-CP-DSA/blob/main/CONTRIBUTING.md) before sending a Pull Request. **Any PR that doesn't adhere to the contributing guidelines will be marked as invalid and closed.**

**Comment by dhyanid13** [comment]
Kindly assign the issue to me I am a regular coder and can work well on this issue

**Comment by sanya-u** [comment]
Kindly assign the issue to me I am a beginner coder and can work well on this issue

**Comment by Vishruth-S** [comment]
This issue is open to all. You can directly send a PR after reading the contribution guidelines

**Comment by jainss** [comment]
Holla, I am really want to code CP-DSA please assign this repo so that i can make awesome changes 😃

**Comment by CSAURABH** [comment]
@Vishruth-S can i work on this issue

**Comment by Vishruth-S** [comment]
This issue is open to all. You can directly send a PR after reading the contribution guidelines
